#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ "${VERSION}" != "image" ]]; then
    if grep -qs "${APP_DIR}" /proc/mounts; then
        echo -e '\e[31m'"Incorrect mount detected! Aborting app installation for security reasons."'\e[0m'
        exit 1
    else
        case "${VERSION}" in
            stable)
                url=$(curl -fsSL "https://api.github.com/repos/lidarr/lidarr/releases" | jq -r .[0].assets[].browser_download_url | grep -o ".*Lidarr.*.linux.tar.gz")
                ;;
            unstable)
                url=$(curl -fsSL "https://services.lidarr.audio/v1/update/nightly/changes?os=linux" | jq -r .[0].url)
                ;;
            *)
                url="${VERSION}"
                ;;
        esac
        rm -rf "${APP_DIR}" && mkdir "${APP_DIR}" && tempfile="$(mktemp)" && curl -fsSL -o "${tempfile}" "${url}" && tar xzf "${tempfile}" -C "${APP_DIR}" --strip-components=1 && chmod -R u=rwX,go=rX "${APP_DIR}" && rm -f "${tempfile}" && INSTALL_OK="yes"
        if [[ "${INSTALL_OK}" != "yes" ]]; then
            echo -e '\e[31m'"Installation of \"${url}\" failed!"'\e[0m'
            exit 1
        fi
    fi
fi
